from datetime import datetime
from pathlib import Path

from jinja2 import Template

from global_econ_agent.models.schemas import DailyReport, ImpactLevel

REPORT_TEMPLATE = """# {{ title }}

> 생성일시: {{ report.generated_at.strftime('%Y-%m-%d %H:%M UTC') }}
> 분석 기사: {{ report.articles_analyzed }}건 / 수집: {{ report.articles_collected }}건

---

## 📋 경영진 요약 (Executive Summary)

{{ report.executive_summary }}

---

## 🔥 주요 핵심 이슈 (Top Issues)

{% for issue in report.key_issues %}
### {{ loop.index }}. {{ issue.title }}

| 항목 | 내용 |
|------|------|
| **영향도** | {{ impact_emoji(issue.impact_level) }} {{ issue.impact_level.value | upper }} |
| **카테고리** | {{ issue.categories | map(attribute='value') | join(', ') }} |
| **영향 지역** | {{ issue.regions_affected | map(attribute='value') | join(', ') }} |
| **주식 영향** | {{ issue.stock_impact }} |
| **채권 영향** | {{ issue.bond_impact }} |
| **금리 전망** | {{ issue.rate_outlook }} |

**요약:** {{ issue.summary_ko }}

{% if issue.affected_sectors %}
**영향 섹터:** {{ issue.affected_sectors | join(', ') }}
{% endif %}
{% if issue.affected_companies %}
**관련 기업:** {{ issue.affected_companies | join(', ') }}
{% endif %}

---
{% endfor %}

## 🔮 시나리오 전망 (Scenario Outlook)

{% for scenario in report.scenarios %}
### {{ scenario.name }} (확률: {{ scenario.probability }})

{{ scenario.description }}

**촉발 요인:**
{% for trigger in scenario.triggers %}- {{ trigger }}
{% endfor %}

| 시장 | 전망 |
|------|------|
| 🇺🇸 미국 | {{ scenario.us_market_outlook }} |
| 🇰🇷 한국 | {{ scenario.kr_market_outlook }} |
| 🇯🇵 일본 | {{ scenario.jp_market_outlook }} |
| 📊 금리 | {{ scenario.rate_outlook }} |

**주요 리스크:**
{% for risk in scenario.key_risks %}- {{ risk }}
{% endfor %}

**💡 투자 시사점:** {{ scenario.investment_implications }}

---
{% endfor %}

## ⚠️ 면책 조항

본 보고서는 AI 에이전트가 공개 뉴스 소스를 기반으로 자동 생성한 참고 자료입니다.
투자 결정의 유일한 근거로 사용해서는 안 되며, 반드시 전문가 상담과 추가 검증이 필요합니다.

---
*Generated by Global Econ Intelligence Agent v0.1*
"""


class ReportBuilder:
    def __init__(self, reports_dir: Path):
        self.reports_dir = reports_dir
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def build(self, report: DailyReport) -> Path:
        template = Template(REPORT_TEMPLATE)
        template.globals["impact_emoji"] = _impact_emoji

        title = f"글로벌 경제 시나리오 보고서 - {report.report_date}"
        markdown = template.render(report=report, title=title)

        filename = f"report_{report.report_date}.md"
        output_path = self.reports_dir / filename
        output_path.write_text(markdown, encoding="utf-8")

        return output_path


def _impact_emoji(level: ImpactLevel) -> str:
    return {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(level.value, "⚪")
